### ISSUE TITLE
new Website Crashes, UI breaks etc

### ISSUE THREAD

**Issue by killbotXD** [devlup-labs/gymkhana_frontend#23]
### Currently Identified Issues 
- [x] Null image url on Office bearers and some society/club pages
-  Add social link redirects to profile edit page
- [x] Top bar does not show Icons on android
- [x] Favicon needs to be updated
- [x] Voulenteer Images should be squares
- [x] Text beneath the Festival Carousel not visible
- [x] Image description on Homepage gallery
- [x] Fix whitespace to the right on mobile devices

**Comment by harsh-not-haarsh** [comment]
Unequal Card size [society card]
![image](https://user-images.githubusercontent.com/44001232/90312925-dfd0ab80-df25-11ea-9fe9-b02ca1ae6ef9.png)
![image](https://user-images.githubusercontent.com/44001232/90312929-e3fcc900-df25-11ea-98ad-3448d3224d82.png)

**Comment by Jashpatel1** [comment]
Dead links
- About Us, Contact Us in footer
- Gymkhana Webd Team

UI
- On hover the cursor can be changed at a few places
- Image description on home page gallery

**Comment by Sandesh1013** [comment]
![gymkhanaa](https://user-images.githubusercontent.com/57478526/90313202-317a3580-df28-11ea-8f36-83091f62f3f2.png)
The text beneath the Festival Carousel in the home page is not visible properly.

**Comment by imraghav20** [comment]
Similar issue as @harsh-not-haarsh mentioned.
Unequal sizes and also poor alignment of cards in "Volunteers" section of clubs.
![issue](https://user-images.githubusercontent.com/59257038/90313228-7b631b80-df28-11ea-8106-09fbc71ee88f.PNG)

**Comment by killbotXD** [comment]
> Dead links
> 
> * About Us, Contact Us in footer
> * Gymkhana Webd Team
> * Help and About in Forum and Konnekt
> 
> UI suggestions
> 
> * On hover the cursor can be changed at a few places
> * Image description on home page gallery

there Is no link for Gymkhana webD team. Might add a link to https://devlup-labs.github.io/#/team

**Comment by killbotXD** [comment]
> Similar issue as @harsh-not-haarsh mentioned.
> Unequal sizes and also poor alignment of cards in "Volunteers" section of clubs.
> ![issue](https://user-images.githubusercontent.com/59257038/90313228-7b631b80-df28-11ea-8106-09fbc71ee88f.PNG)

It isn't poor alignment @imraghav20 . Actually there are 6 voulenteers but due to some null value only 3 are being shown, which is in the issue description.

**Comment by imraghav20** [comment]
> > Similar issue as @harsh-not-haarsh mentioned.
> > Unequal sizes and also poor alignment of cards in "Volunteers" section of clubs.
> > ![issue](https://user-images.githubusercontent.com/59257038/90313228-7b631b80-df28-11ea-8106-09fbc71ee88f.PNG)
> 
> It isn't poor alignment @imraghav20 . Actually there are 6 voulenteers but due to some null value only 3 are being shown, which is in the issue description.

OK @killbotXD . Thanks for clarification.

**Comment by ajatprabha** [comment]
@killbotXD prioritise the bugs in an order and prepare for a release after the fixes.
Also, does a checked box in the issue description mean that it has been fixed?

**Comment by killbotXD** [comment]
checkbox = Fixed but not pushed 😅
