### ISSUE TITLE
In Konnekt, every user has the same Gender and Branch as of the logged in user

### ISSUE THREAD

**Issue by imraghav20** [devlup-labs/gymkhana_frontend#27]
Whenever a "Male" user logs in the Gymkhana portal, every other user's gender is shown as "Male" irrespective of he/she has filled "Male"/"Female". Similarly, whenever a "Female" user logs in the portal, every other user's gender is shown "Female".
Also, if a user of CSE branch logs in to the portal, for every other user shows CSE branch, irrespective of the branch the other user has filled. Same applies if user of any other branch logs in.

**Comment by killbotXD** [comment]
No issue In frontend
