### ISSUE TITLE
Add Dark theme and Toggle button

### ISSUE THREAD

**Issue by killbotXD** [devlup-labs/gymkhana_frontend#33]
create a toggle button to toggle between light and dark themes in the Header or side nav

**Comment by PeterJanic** [comment]
Hi i would like to work on this issue. Can I be assigned to this?

**Comment by killbotXD** [comment]
Sure go ahead

**Comment by killbotXD** [comment]
@PeterJanic You would need to setup the backend server from [here](https://github.com/devlup-labs/gymkhana_portal). You can manually add dummy data for testing or populate the DB with random values for testing using the `createfixture` command (it takes some time to create dummy data)

After the [backend server](https://github.com/devlup-labs/gymkhana_portal) is running you need to change 2 lines in the [config](../tree/master/src/plugins/vue-apollo.js) file

1) [line 15](https://github.com/devlup-labs/gymkhana_frontend/blob/a70f3b3f35ee8e2c9768ec840512d0e3502799a5/src/plugins/vue-apollo.js#L15)  ```const httpEndpoint = process.env.VUE_APP_GRAPHQL_HTTP || "/graphql";```
 to ```const httpEndpoint = process.env.VUE_APP_GRAPHQL_HTTP || "http://127.0.0.1:8000/graphql";``` 
2) [line 52](https://github.com/devlup-labs/gymkhana_frontend/blob/a70f3b3f35ee8e2c9768ec840512d0e3502799a5/src/plugins/vue-apollo.js#L52) ```httpEndpoint: "/pgraphql"``` 
to ```httpEndpoint: "http://127.0.0.1:8000/pgraphql"```

And then start the Vue server using `npm run serve` 
Feel free to ask if you have any queries or issues.

**Comment by PeterJanic** [comment]
Sorry, I am not able to do this issue.

**Comment by VishalZ123** [comment]
Hello, I would like to work on this issue. Will you please assign me the issue?

**Comment by killbotXD** [comment]
Assigning @VishalZ123 the Issue.
